// The narration drives the film's timing, and then rides on the rendered picture.
//   bun build-voice.ts timing   measures voice/<lang>/NN.mp3 and writes timing.js, which the film loads
//   bun build-voice.ts [film]   lays the voice on out/sbarbase-explainer.mp4 (or [film]) and writes the
//                               site media: one MP4 and one WebVTT file per language
// Cues follow each other with a short breath, timed by the longer of the two languages, so neither
// language has a long silence; the check below fails when one would.
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

type Cue = { file: string; scene: string; ar: string; en: string };
type Spec = { gap: number; lead: number; tail: number; cues: Cue[] };
const LANGS = ['ar', 'en'] as const, MAX_SILENCE = 0.9;
const here = import.meta.dir;
const spec: Spec = await Bun.file(path.join(here, 'narration.json')).json();
const run = (cmd: string, args: string[]) => execFileSync(cmd, args, { encoding: 'utf8' }).trim();
const seconds = (f: string) => Number(run('ffprobe', ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', f]));
const round = (t: number) => Math.round(t * 1000) / 1000;
const stamp = (t: number) => { const m = Math.floor(t / 60), s = t - m * 60; return `${String(m).padStart(2, '0')}:${s.toFixed(3).padStart(6, '0')}`; };
// each recording, with the silence the voice service leaves at its start and end trimmed off
const trimmed = path.join(here, 'out', 'voice', 'trimmed');
const clip = (lang: string, c: Cue) => path.join(trimmed, lang, `${c.file}.wav`);
for (const lang of LANGS) { mkdirSync(path.join(trimmed, lang), { recursive: true });
  for (const c of spec.cues) run('ffmpeg', ['-v', 'error', '-y', '-i', path.join(here, 'voice', lang, `${c.file}.mp3`), '-af',
    'silenceremove=start_periods=1:start_threshold=-45dB,areverse,silenceremove=start_periods=1:start_threshold=-45dB,areverse,adelay=40:all=1', clip(lang, c)]); }

// cue starts, scene boundaries and the total length, from the measured clips
const lengths = spec.cues.map(c => Object.fromEntries(LANGS.map(l => [l, seconds(clip(l, c))])) as Record<string, number>);
const starts: number[] = []; let t = spec.lead;
spec.cues.forEach((_, k) => { starts.push(round(t)); t += Math.max(...LANGS.map(l => lengths[k]![l]!)) + spec.gap; });
const total = round(t - spec.gap + spec.tail);
const scenes: { name: string; start: number; dur: number; cues: number[]; lens: number[] }[] = [];
spec.cues.forEach((c, k) => { let s = scenes.at(-1);
  if (!s || s.name !== c.scene) { const start = k === 0 ? 0 : round(starts[k]! - 0.15); if (s) s.dur = round(start - s.start); s = { name: c.scene, start, dur: 0, cues: [], lens: [] }; scenes.push(s); }
  s.cues.push(round(starts[k]! - s.start)); s.lens.push(round(Math.max(...LANGS.map(l => lengths[k]![l]!)))); });
scenes.at(-1)!.dur = round(total - scenes.at(-1)!.start);
for (const l of LANGS) spec.cues.forEach((c, k) => { if (k === 0) return; const silence = starts[k]! - (starts[k - 1]! + lengths[k - 1]![l]!);
  if (silence > MAX_SILENCE) throw new Error(`${l}: ${silence.toFixed(2)}s of silence before cue ${c.file}; shorten or speed up the longer language`); });

if (process.argv[2] === 'timing') {
  writeFileSync(path.join(here, 'timing.js'), `// Generated by build-voice.ts from narration.json and the recorded voice. Do not edit.\nwindow.TIMING = ${JSON.stringify({ total, scenes })};\n`);
  console.log(`timing.js: ${total}s, ${scenes.map(s => `${s.name} ${s.dur}s`).join(', ')}`);
  process.exit(0);
}

const film = path.resolve(process.argv[2] ?? path.join(here, 'out', 'sbarbase-explainer.mp4'));
const media = path.join(here, '..', 'website', 'public', 'media');
const tmp = path.join(here, 'out', 'voice');
if (Math.abs(seconds(film) - total) > 0.1) throw new Error(`film is ${seconds(film)}s, the narration needs ${total}s; run \`bun build-voice.ts timing\` and render again`);
for (const lang of LANGS) {
  const inputs = spec.cues.flatMap(c => ['-i', clip(lang, c)]);
  const delays = spec.cues.map((_, k) => `[${k}:a]adelay=${Math.round(starts[k]! * 1000)}:all=1[a${k}]`).join(';');
  const mix = `${delays};${spec.cues.map((_, k) => `[a${k}]`).join('')}amix=inputs=${spec.cues.length}:normalize=0,loudnorm=I=-16:TP=-1.5,apad,atrim=0:${total}[v]`;
  const voice = path.join(tmp, `${lang}.m4a`);
  run('ffmpeg', ['-v', 'error', '-y', ...inputs, '-filter_complex', mix, '-map', '[v]', '-c:a', 'aac', '-b:a', '96k', '-ac', '1', voice]);
  run('ffmpeg', ['-v', 'error', '-y', '-i', film, '-i', voice, '-map', '0:v:0', '-map', '1:a:0', '-c:v', 'libx264', '-crf', '22',
    '-preset', 'slow', '-pix_fmt', 'yuv420p', '-c:a', 'copy', '-movflags', '+faststart', '-shortest', path.join(media, `explainer.${lang}.mp4`)]);
  const vtt = ['WEBVTT', '', ...spec.cues.flatMap((c, k) => [`${stamp(starts[k]!)} --> ${stamp(starts[k]! + lengths[k]![lang]! + 0.2)}`, c[lang], ''])].join('\n');
  writeFileSync(path.join(media, `explainer.${lang}.vtt`), vtt);
  console.log(`explainer.${lang}.mp4 and .vtt written`);
}
