import {mkdir,cp,rm} from 'node:fs/promises';
import {render} from './src/render';
await rm(new URL('./dist',import.meta.url),{recursive:true,force:true});
await mkdir(new URL('./dist/en',import.meta.url),{recursive:true});
await cp(new URL('./public',import.meta.url),new URL('./dist',import.meta.url),{recursive:true});
await Bun.write(new URL('./dist/index.html',import.meta.url),render('ar'));
await Bun.write(new URL('./dist/en/index.html',import.meta.url),render('en'));
await Bun.write(new URL('./dist/style.css',import.meta.url),Bun.file(new URL('./src/style.css',import.meta.url)));
await Bun.write(new URL('./dist/app.js',import.meta.url),Bun.file(new URL('./src/app.js',import.meta.url)));
await Bun.write(new URL('./dist/404.html',import.meta.url),'<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Page not found | Sbarbase</title><link rel="stylesheet" href="/style.css"><body><main class="container section"><h1>Page not found.</h1><p><a href="/">Return to Sbarbase</a></p></main></body></html>');
console.log('Built Arabic and English pages.');
