import {useEffect,useState} from 'react';
import {ArrowLeft,Plus,ChevronRight,RotateCw,Pencil,Trash2} from 'lucide-react';
import {useData,type Api,type Organization,type Project,type Environment} from './api';
import {Empty,ErrorMessage,Loading,NameForm,Refresh} from './components';
const labels:Record<string,string>={queued:'Queued',running:'Provisioning',succeeded:'Provisioned',failed:'Failed',cancelled:'Cancelled'};
/** Rename, move and delete the project. Owners and admins rename; only owners move (to another
 * organization they own) and delete. Moving revokes the project's API keys. */
function ProjectSettings({project,organization,request,empty,onDone}:{project:Project;organization:Organization;request:Api;empty:boolean;onDone:()=>void}){
 const owned=useData<{data:Organization[]}>(signal=>request('/organizations','GET',undefined,signal),[request]);
 const [renaming,setRenaming]=useState(false),[target,setTarget]=useState(''),[confirm,setConfirm]=useState<'move'|'delete'>(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const destinations=owned.data?.data.filter(item=>item.role==='owner'&&item.id!==organization.id)??[];
 async function act(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();onDone();}catch(e){setError((e as Error).message);}finally{setBusy(false);setConfirm(undefined);}}
 return <section className="details" aria-labelledby="project-settings"><h2 id="project-settings">Project settings</h2>
 {renaming?<NameForm label="New project name" action="Rename" onCancel={()=>setRenaming(false)} onSubmit={async name=>{await request(`/projects/${project.id}`,'PATCH',{name});setRenaming(false);onDone();}}/>:<button disabled={busy} onClick={()=>setRenaming(true)}><Pencil aria-hidden="true"/>Rename project</button>}
 {organization.role==='owner'&&<>{destinations.length>0&&<div className="form-row"><label htmlFor="move-target">Move to</label><select id="move-target" value={target} onChange={event=>setTarget(event.target.value)}><option value="">Choose an organization</option>{destinations.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>
 {confirm==='move'?<div className="confirm"><span>Move it? Its API keys stop working and must be issued again.</span><button className="danger" disabled={busy} onClick={()=>void act(()=>request(`/projects/${project.id}/move`,'POST',{organization:target}))}>Confirm move</button><button onClick={()=>setConfirm(undefined)}>Cancel</button></div>:<button disabled={busy||!target} onClick={()=>setConfirm('move')}>Move project</button>}</div>}
 {confirm==='delete'?<div className="confirm"><span>Delete this project?</span><button className="danger" disabled={busy} onClick={()=>void act(()=>request(`/projects/${project.id}`,'DELETE'))}>Confirm delete</button><button onClick={()=>setConfirm(undefined)}>Cancel</button></div>:<button disabled={busy||!empty} title={empty?undefined:'Delete its environments first'} onClick={()=>setConfirm('delete')}><Trash2 aria-hidden="true"/>Delete project</button>}</>}
 <ErrorMessage message={error}/></section>;
}
export function Environments({project,organization,request,onBack,onSelect}:{project:Project;organization:Organization;request:Api;onBack:()=>void;onSelect:(environment:Environment)=>void}){
 const result=useData<Environment[]>(async signal=>(await request(`/projects/${project.id}/environments`,'GET',undefined,signal) as {data:Environment[]}).data,[project.id,request]);
 const [creating,setCreating]=useState(false),[retryError,setRetryError]=useState(''),[renaming,setRenaming]=useState<string>(),[deleting,setDeleting]=useState<string>();
 const manage=organization.role!=='viewer';
 const remove=async(environment:Environment)=>{setRetryError('');try{await request(`/environments/${environment.id}`,'DELETE');setDeleting(undefined);result.refresh();}catch(error){setRetryError(error instanceof Error?error.message:'Delete failed.');}};
 const retry=async(environment:Environment)=>{setRetryError('');try{await request(`/environments/${environment.id}/retry`,'POST');result.refresh();}catch(error){setRetryError(error instanceof Error?error.message:'Retry failed.');}};
 const pending=result.data?.some(item=>['queued','running'].includes(item.state??''));
 useEffect(()=>{if(!pending)return;const timer=setTimeout(result.refresh,3000);return()=>clearTimeout(timer);},[pending,result.data]);
 return <><button className="back" onClick={onBack}><ArrowLeft aria-hidden="true"/>Projects</button><div className="page-heading"><div><h1>{project.name}</h1><p className="muted">Environments</p></div>{organization.role!=='viewer'&&<button className="primary" disabled={creating} onClick={()=>setCreating(true)}><Plus aria-hidden="true"/>New environment</button>}</div>
 {creating&&<NameForm label="Environment name" onCancel={()=>setCreating(false)} onSubmit={async name=>{await request(`/projects/${project.id}/environments`,'POST',{name});setCreating(false);result.refresh();}}/>}
 <div className="toolbar"><span className="muted small">Provisioning status</span><Refresh onClick={result.refresh}/></div><ErrorMessage message={result.error||retryError}/>{result.loading?<Loading/>:result.data?.length?<div className="table-wrap"><table><thead><tr><th>Environment</th><th>Status</th><th>Connection</th>{manage&&<th>Manage</th>}</tr></thead><tbody>{result.data.map(environment=><tr key={environment.id}><td>{environment.name}</td><td><span className={'state '+environment.state}>{environment.state==='failed'&&environment.failure==='capacity_exceeded'?'Capacity limit':labels[environment.state??'']??'Unknown'}</span></td><td>{environment.state==='succeeded'?<button onClick={()=>onSelect(environment)}>Connect<ChevronRight aria-hidden="true"/></button>:['failed','cancelled'].includes(environment.state??'')&&organization.role!=='viewer'?<button onClick={()=>void retry(environment)}><RotateCw aria-hidden="true"/>Retry</button>:<span className="muted small">Not available yet</span>}</td>
 {manage&&<td><div className="form-row"><button onClick={()=>setRenaming(environment.id)}><Pencil aria-hidden="true"/>Rename</button>{organization.role==='owner'&&(deleting===environment.id?<div className="confirm"><span>Delete {environment.name}? Its API keys stop working. Its data is kept on the server.</span><button className="danger" onClick={()=>void remove(environment)}>Confirm delete</button><button onClick={()=>setDeleting(undefined)}>Cancel</button></div>:<button onClick={()=>setDeleting(environment.id)}><Trash2 aria-hidden="true"/>Delete</button>)}</div></td>}</tr>)}</tbody></table></div>:!result.error&&<Empty>No environments yet. Create one to connect your application.</Empty>}
 {renaming&&<NameForm label="New environment name" action="Rename" onCancel={()=>setRenaming(undefined)} onSubmit={async name=>{await request(`/environments/${renaming}`,'PATCH',{name});setRenaming(undefined);result.refresh();}}/>}
 {manage&&result.data&&<ProjectSettings project={project} organization={organization} request={request} empty={!result.data.length} onDone={onBack}/>}
 {pending&&<p className="notice" role="status">Your environment is waiting for the installation worker. This page updates automatically.</p>}
 {result.data?.some(item=>item.state==='failed'&&item.failure==='capacity_exceeded')&&<p className="notice">This installation cannot admit another environment within its configured capacity limits. Ask the installation owner to review capacity before retrying.</p>}
 {result.data?.some(item=>item.state==='failed'&&item.failure!=='capacity_exceeded')&&<p className="notice">{organization.role==='viewer'?'Provisioning failed. Ask an owner or admin of this organization to retry it.':'Provisioning failed. Retry it; if it fails again, ask the installation owner to inspect the worker.'}</p>}</>;
}
